---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: localstack-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/localstack"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localstack-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  type: NodePort
  selector:
    app: localstack
  ports:
    - name: edge
      port: 4566
      nodePort: 30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3.0
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "secretsmanager,cloudformation,dynamodb"
            - name: PERSISTENCE
              value: "1"
            - name: DEBUG
              value: "0"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: "/var/lib/localstack"
              name: localstack-data
          readinessProbe:
            httpGet:
              path: /_localstack/health
              port: 4566
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: localstack-data
          persistentVolumeClaim:
            claimName: localstack-pv-claim         